request to merge vocal-contour
Music-and-Culture-Technology-Lab/omnizart pull request #7
Opened 2020-11-27 05:50 UTC by yjlolo

This is to add `vocal-contour` which adapts repo from the [original repo](https://github.com/s603122001/Vocal-Melody-Extraction).

- The PR provides the essential functionality to `transcribe`, `generate_feature`, and `train` for frame-level vocal melody extraction, which also serves as the foundation for the note-level vocal melody transcription under development.
- One missing feature is preprocessing of `MedleyDB`; so training the model with data mixing `MIK-1K` and `MedleyDB` as in the [paper](https://archives.ismir.net/ismir2018/paper/000286.pdf) is disabled currently. Despite the missing feature, the model checkpoint `Seg` from the [link to checkpoints provided in the original repo](https://drive.google.com/file/d/13kApyZ5lJEGE5CDwaeEuxVuw9sZy_xae/view) is implemented and provided in this PR.
- Another missing feature is the accommodation of different variations of models (e.g. progressive ones, refer to the [paper](https://archives.ismir.net/ismir2018/paper/000286.pdf) for more detail). The implemented model is `Seg`, which performs the best according to our experiments.
- Documentation is to be updated.

2020-11-28 10:04 UTC, BreezeWhite requested changes
Some more things to be added:

- [ ] Add unit tests. At least add test of loading checkpoints like [here](https://github.com/Music-and-Culture-Technology-Lab/omnizart/blob/master/tests/music/test_app.py).
- [ ] Make sure passing the `general-check` before merging. Seems like there are still problems with the dependencies.

Great thanks to your huge contributions^^.

2020-11-30 04:06 UTC, yjlolo commented on omnizart/vocal_contour/app.py
> +            save_to = output
This was to be consistent with [`music.app`](https://github.com/Music-and-Culture-Technology-Lab/omnizart/blob/d27412bdc57da9f646a2ae244796bb5569af13ff/omnizart/music/app.py#L113).

2020-11-30 07:57 UTC, yjlolo commented on omnizart/cli/vocal_contour/train_model.py
> +@click.option("-t", "--timesteps", help="Time width of each input feature", type=int, default=128)
I was following the same line from [`music`](https://github.com/Music-and-Culture-Technology-Lab/omnizart/blob/d27412bdc57da9f646a2ae244796bb5569af13ff/omnizart/cli/music/train_model.py#L46). 
I suppose there is a better way to pass the default values from the setting, and at the same time allow the optional argument as the input?

2020-12-02 04:26 UTC, yjlolo commented on omnizart/cli/vocal_contour/generate_feature.py
> +)
The purpose here is to show which variables could be critical for resulted transcription accuracy.
(Re-)setting default values here is to be able to `show_default` for the users when `--help` is called, so they can assign to other values if needed. What do you think?

2020-12-08 08:07 UTC, BreezeWhite approved these changes

2020-12-08 08:27 UTC, merged